#!/usr/bin/perl -w

# similar to 'mk-packlist' but try to generate as compact XML as possible

use strict;
use ActiveState::Handy qw(cat);

my $os = shift || $^O;

print qq(<?xml version="1.0" encoding="UTF-8"?>
<pkglist>
);

opendir(my $dh, $os) || die;
while (defined(my $f = readdir($dh))) {
    next unless $f =~ /\.ppd$/;
    $_ = cat("$os/$f");
    s/^\s*<\?xml\s[^>]*>\s*//;
    s/^\s*<OS NAME="[^"]*"\s*\/>\n?//m;
    s/^\s*<(CODEBASE|ARCHITECTURE)[^>]*>\n?//mg;
    s/^\s*<\/?IMPLEMENTATION>\n?//mg;
    s/^\s*<TITLE>[^<]+<\/TITLE>\n?//m;

    # shorten markup
    s/ NAME=/ n=/g;
    s/( VERSION="\d+,\d+),0,0"/$1"/g;
    s/ VERSION=/ v=/g;
    s/(<\/?)SOFTPKG/$1pkg/g;
    s/(<\/?)ABSTRACT/$1a/g;
    s/(<\/?)AUTHOR/$1m/g;
    s/(<\/?)DEPENDENCY/$1d/g;
    s/>\s+</></g;  # kill space between elements
    s/"\s+\/>/"\/>/g;
    print;
}

print "</pkglist>\n";
